name: fit_list
description: A gym workout to-do list app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.2.0    
  flutter_mobx: ^2.0.6+5
  google_fonts: ^5.1.0
  image_picker: ^1.0.1
  cached_network_image: ^3.2.3
  path_provider: ^2.0.15
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/preset_workouts.json
